### ISSUE TITLE
Decide on a "globally unique identifier" format

### ISSUE THREAD

**Issue by Sebmaster** [jsdom/whatwg-url#10]
The URL spec defines that origin may return a "globally unique identifier", which isn't described any further (see also whatwg/url#21).

In cases where the scheme isn't known, Chrome just returns `scheme + "://"`. Should we just keep to Chrome here, @domenic?

**Comment by domenic** [comment]
Whereas `new URL("accc://abcsdd.com/adf").origin` in Firefox returns `"null"` (the string). Bizarre.

**Comment by Sebmaster** [comment]
Aligned with Chrome for now, will revisit when spec is updated or browsers unify their behaviour.

**Comment by annevk** [comment]
Wait wait wait... The origin is a globally unique identifier. However, when you serialize that to a string (defined elsewhere) you get "null". So Chrome has a bug.

**Comment by Sebmaster** [comment]
Great, aligned with 0583900. Still gotta think about what to return with file:/// URLs. Firefox returns "", Chrome returns "file://".

**Comment by domenic** [comment]
Some stuff to read (haven't done so myself yet):

- https://code.google.com/p/chromium/issues/detail?id=455882
- https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file:_URIs

**Comment by TimothyGu** [comment]
Has this been fixed? The URL Standard now no longer contains any reference to "globally unique identifier".

**Comment by annevk** [comment]
You can search for "opaque origin" these days. It's basically the same thing.

**Comment by domenic** [comment]
This can probably be closed since it'd be more of a jsdom-level concern (since it's about the opaque origin concept), not a whatwg-url concern (since that only produces serializations).
