### ISSUE TITLE
new.target use causes errors in Node v4.

### ISSUE THREAD

**Issue by jdalton** [jsdom/whatwg-url#104]
I'm not sure what versions of Node are supported but noticed Node v4 [erroring](http://node.green/#ES2015-syntax-new-target) because of `new.target` use.

**Comment by TimothyGu** [comment]
Only Node.js v6.x+ are supported in the latest version. For Node.js v4.x support you have to use whatwg-url v5.x (or below). See also https://github.com/jsdom/whatwg-url/issues/96.

**Comment by jdalton** [comment]
@TimothyGu Ah, should probably be called out in the readme. I was looking for an engines field or something but couldn't come up with anything.

**Comment by iamdey** [comment]
There's a plugin for babel, unfortunately it will be available for babel 7

https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-new-target

_(I have the same issue with webpack uglify js plugin that requires code be compiled in es5)_

**Comment by jan-auer** [comment]
FWIW, @iamdey, the Babel Plugin alone wouldn’t help. new.target isn’t the only issue causing Node 4 to crash. The code also contains destructuring assignments etc, which are not supported in v4 afaik. 

In addition to what @jdalton said, it would also be great, if the node engine requirement was declared in package.json

**Comment by stevenvachon** [comment]
[universal-url](https://npmjs.com/universal-url)

**Comment by adipascu** [comment]
This also crashes when using Fetch As Google. Usage of ES6 features in published npm packages must be documented. There is currently an unwritten rule to only publish ES5 code.
