### ISSUE TITLE
Publish this package pre-compiled

### ISSUE THREAD

**Issue by justafish** [jsdom/whatwg-url#105]
Thanks for the library!

When trying to bundle for production with create-react-app I get the following error:
```
Failed to minify the code from this file: 

 	./node_modules/whatwg-url/lib/url-state-machine.js:6 
```

According to https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify I should "Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled (retaining ES6 Modules)." 😁

**Comment by domenic** [comment]
Sorry, we're not interested in supporting old Node.js versions or tooling that doesn't recognize modern JavaScript syntax.

**Comment by ThomasVuillaume** [comment]
Well, I dont really understand... I have the same issue 

`> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/whatwg-url/lib/url-state-machine.js:6

Read more here: http://bit.ly/2tRViJ9`

But I'm on node v10.11.0. Any clue here ?
