### ISSUE TITLE
Create our own or support live URL viewer, via CI

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#106]
https://quuz.org/url/liveview.html by @annevk is great but it's not kept up to date, I don't believe.

The jsdom project should ideally help with this, e.g. by deploying a live URL viewer of this sort to our gh-pages branch via CI.

**Comment by annevk** [comment]
I'm also happy to grant access to https://github.com/annevk/live-url-viewer to make it automatically deploy somehow.

**Comment by Sebmaster** [comment]
We should be able to make travis auto deploy to a gh-pages branch with any updates, either to @annevk's repo, or to a branch on this one.

@annevk Any preference?

**Comment by annevk** [comment]
I guess I'd prefer not to be responsible for any gh-pages myself. I don't like being locked to GitHub's domain.

**Comment by domenic** [comment]
Deployed to https://jsdom.github.io/whatwg-url/! Still missing the setter functionality from https://quuz.org/url/liveview3.html but otherwise I'm happy with it.
