### ISSUE TITLE
Safari can't load URL.js 

### ISSUE THREAD

**Issue by mikemaccana** [jsdom/whatwg-url#108]
Safari in macOS High Sierra and iOS 11.02 13604.1.38.1.6 fails on `URL.js` with: 

> new.target can't come after a prefix operator

Issue is webkit, but workaround needs to be applied to `webidl2js` (and a new version of `whatwg-url` built). See https://github.com/jsdom/webidl2js/issues/78.

**Comment by baztypetrucci** [comment]
Thank you for the fix, this is necessary! 😁

**Comment by darylteo** [comment]
@baztypetrucci I'll just point you to this [Comment](https://github.com/jsdom/webidl2js/issues/90#issuecomment-341322538) which makes it clear that:

> only Node is supported.

For your info.

**Comment by mikemaccana** [comment]
Or the full comment:

> This is really only intended for Node or **browsers with JavaScript as good as Node.**

**Comment by baztypetrucci** [comment]
@darylteo this package is used by Nuxt (VUE.js) for making web apps, obviusly this is crashing on every nuxt app rendering on iOS Safari or mac Safari. This is critical.

**Comment by TimothyGu** [comment]
The issue has already been fixed in webidl2js, which is the component that generates the problematic file automatically. We just need to release a new version, which unfortunately has not happened yet since this is a spare-time project. Please try to be patient over the next days, since it's Thanksgiving Day in the United States, before either @domenic or @Sebmaster could upgrade webidl2js and release a new version.

**Comment by Skwai** [comment]
Also preventing my phantomJS tests from running :(

**Comment by idris** [comment]
@domenic or @Sebmaster could you please release a new version with this fix?

**Comment by TimothyGu** [comment]
@domenic and @Sebmaster I've just created a [jsdom](https://www.npmjs.com/org/jsdom) npm organization containing people in @jsdom. If one of you could make the organization an owner of the jsdom packages including whatwg-url then we could help fix this ASAP.

**Comment by stevenvachon** [comment]
[universal-url](https://npmjs.com/universal-url)

**Comment by benjaminbillet** [comment]
Is this problem corrected? It still happen in my app with whatwg-url 6.4.1
