### ISSUE TITLE
different results in parsing hostname / origin with custom uri schemes

### ISSUE THREAD

**Issue by jsuarezatzendesk** [jsdom/whatwg-url#110]
in Chrome:
```js
a = new URL('abc://a123/foo/1')
[a.protocol, a.host, a.hostname, a.pathname]
// ["abc:", "", "", "//a123/foo/1"]


b = new URL('http://a123/foo/1')
[b.protocol, b.host, b.hostname, b.pathname]
// ["http:", "a123", "a123", "/foo/1"]
```

with whatwg-url 6.3.0:
```js
a = new URL('abc://a123/foo/1')
[a.protocol, a.host, a.hostname, a.pathname]
// [ 'abc:', 'a123', 'a123', '/foo/1' ]

b = new URL('http://a123/foo/1')
[b.protocol, b.host, b.hostname, b.pathname]
// [ 'http:', 'a123', 'a123', '/foo/1' ]
```

**Comment by Sebmaster** [comment]
We're not going off of Chrome behaviour, we're going off of the [URL Standard](https://url.spec.whatwg.org/).

If you believe this to be a bug in the standard, report it [here](https://github.com/whatwg/url). If you believe this to be a bug in the implementation, we'll need some info on where in the standard we're going wrong. Alternatively, Chrome's behaviour might actually be buggy here.

**Comment by TimothyGu** [comment]
From a quick looks, it seems to me that Chrome is the buggy party here by not implementing https://github.com/whatwg/url/commit/b266a43fc9df0e8607074bd4d336a517e2010009 properly. Per the current URL Standard, there should be a difference between `abc:/a123/foo/1` (which has a path of `/a123/foo/1`) and `abc://a123/foo/1` (which should be parsed just like any HTTP URLs). It seems non-sensical to me how `new URL('/root', 'abc://a123/foo').pathname` could result in `'//a123/root'`, which is what Chrome outputs.

**Comment by felixfbecker** [comment]
Did anyone file this on Chrome? Firefox also has the same bug
