### ISSUE TITLE
href setter does not propagate to URL.searchParams

### ISSUE THREAD

**Issue by Zirro** [jsdom/whatwg-url#111]
This is covered by the last test in https://github.com/w3c/web-platform-tests/blob/master/url/url-constructor.html (which probably should be included among the tests in this repo as well?).

I can get it to pass by adding:

```JavaScript
const query = parsedURL.query !== null ? parsedURL.query : "";

this._query = URLSearchParams.createImpl([query], { doNotStripQMark: true });
```

...to the `href` setter while also removing the `getSameObject()`-logic from the generated file, but obviously a cleaner solution is needed.

**Comment by domenic** [comment]
Hmm, yeah, it looks like we just totally forgot to implement most of https://url.spec.whatwg.org/#dom-url-href

**Comment by Sebmaster** [comment]
Yeah, searchParams was initially unimplemented so we skipped those steps in the href setter. Seems like when the impl came we didn't update that...
