### ISSUE TITLE
Unable to pass onto nodejs' native url format fn

### ISSUE THREAD

**Issue by binarykitchen** [jsdom/whatwg-url#112]
Nodejs has a native format function for url objects. But it seems it doesn't accept instances from whatwg-url. For example this custom function to strip queries isn't going to work:

```js
import { URL } from 'whatwg-url'
import { format } from 'url'

export default function (urlStr = window.location.href) {
  const url = new URL(urlStr)

  return format(url, {
    auth: false,
    search: false
  })
}
```

**Comment by Sebmaster** [comment]
That's not a bug in this library.

**Comment by binarykitchen** [comment]
then what it is @Sebmaster ?

**Comment by Sebmaster** [comment]
I don't know what you're expecting here, they just don't work together and are not intended to.

**Comment by binarykitchen** [comment]
alright - reworded: how can i strip query parameters best?

**Comment by Sebmaster** [comment]
```js
x = new URL("http://me:pass@example.org/?query=abc")
x.search = x.username = x.password = "";
console.log(x.href)
```

**Comment by binarykitchen** [comment]
right, thanks!

a bit magical that altering one object attribute changes another object attribute - functions should do that

**Comment by Sebmaster** [comment]
We didn't create the API, browsers did. We just implemented it.
