### ISSUE TITLE
Change origin getter result for file: URLs to "null"

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/whatwg-url#117]
https://url.spec.whatwg.org/#concept-url-origin says:

> A URL’s **origin** is the [origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin) returned by running these steps, switching on URL’s scheme:
>
> …
>
> <dl><dt>"<code>file</code>"</dt><dd>Unfortunate as it is, this is left as an exercise to the reader. When in doubt, return a new <a href="https://html.spec.whatwg.org/multipage/origin.html#concept-origin-opaque">opaque origin</a>.</dd></dl>

**Comment by TimothyGu** [comment]
https://github.com/jsdom/whatwg-url/blob/4a073d8641307c377ef736d320616018c17c25e4/src/url-state-machine.js#L1250-L1252

**Comment by TimothyGu** [comment]
See also https://github.com/nodejs/node/issues/21955

**Comment by domenic** [comment]
+1 on this, although it may be a major version bump since it changes the same-originness of file URLs?
