### ISSUE TITLE
Documentation for consuming whatwg-url

### ISSUE THREAD

**Issue by benlakey** [jsdom/whatwg-url#119]
As an author looking to consume this package: There is no documentation about how to use/consume this library in the README.  I'd love to contribute those docs, but I have no idea what they would say (thats what I'm looking for). Help?

**Comment by domenic** [comment]
Are you familiar with how npm packages normally work?

**Comment by benlakey** [comment]
@domenic Yes...   I'm not referring to how to use npm packages I'm referring to how you would consume the API.  I'm not referring to how npm packages work or how module systems work.  

> "whatwg-url is a full implementation of the WHATWG URL Standard. It can be used standalone, but it also exposes a lot of the internal algorithms that are useful for integrating a URL parser into a project like jsdom."

That from the README says you can use it in 2 ways:

1. Standalone
2. Integrated with jsdom

There is nothing in the documentation that expands upon how you might use it in a standalone fashion (why would you want to? what use-case? what are some examples?)  or integrated with jsdom (why would you want to? what use-case? what are some examples?)

**Comment by domenic** [comment]
The readme documents the API pretty clearly, telling you what the exports are. If you're aware of how to use npm packages, e.g. that they export things, then this should be all the documentation you need.

As for why you might want to use a URL parser, if you don't know that, this package isn't the place to explain it to you :)

**Comment by benlakey** [comment]
Alright it seems pretty clear you are not open to improving the docs as they stand. Thanks for your time.
