### ISSUE TITLE
Can we use typed arrays instead of Buffers?

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#12]
Buffers are such a Node thing... Besides, it's confusing that sometimes in the implementation buffer means a string and sometimes a Node `Buffer` object.

Uint8Array is probably what you want.

**Comment by Sebmaster** [comment]
The problem is converting the string to a byte sequence, encoded with utf8. Uint8Array doesn't have anything specific which does this conversion, maybe there's something in punycode which does the conversion properly, or we have to see how `Buffer` implements the encoding.

**Comment by domenic** [comment]
Ah I see. Yeah, to do that in browsers you'd have to use TextEncoder, which Node doesn't have :(.

In theory we could factor this out into a module whose browserify version used TextEncoder and whose node version used Buffer. But that seems like overkill. Buffer is fine until we can get TextEncoder into Node somehow.

**Comment by stevenvachon** [comment]
I think that this is worth reopening. Buffer is pretty big.

**Comment by domenic** [comment]
Pull request welcome, but it's not a priority for us to track.

**Comment by stevenvachon** [comment]
https://github.com/inexorabletash/text-encoding

**Comment by stevenvachon** [comment]
This looks reasonable: https://gist.github.com/pascaldekloe/62546103a1576803dade9269ccf76330

**Comment by stevenvachon** [comment]
Or https://npmjs.com/utf8
