### ISSUE TITLE
Transpiled build for bundlers

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#126]
Would you be opposed to a PR that provided a transpiled—but not bundled—build for reference in the `browser` package.json key? This would prevent the need for performing such on this as a dependency within each project.

* It could be part of the test suite.
* A few simple tests could be ran with [puppeteer](https://npmjs.com/puppeteer).
* There could be `es5` and `esnext` dirs for separating source.

**Comment by domenic** [comment]
Yes, we would. This is the consumer's responsibility.

**Comment by stevenvachon** [comment]
There are risks in transpiling dependencies. It should be appropriately handled by the author.

**Comment by domenic** [comment]
I understand that we disagree, but this project is maintained by someone with a different philosophy than you.

**Comment by stevenvachon** [comment]
And that philosophy is wrong!!
