### ISSUE TITLE
Feature request: createObjectURL

### ISSUE THREAD

**Issue by ukch** [jsdom/whatwg-url#129]
See https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

**Comment by geeeger** [comment]
😔same problem

**Comment by domenic** [comment]
This is outside the scope of this project, as it would involve supporting Blobs, the blob URL store, etc. Instead it would be part of jsdom. Track that at https://github.com/jsdom/jsdom/issues/1721.
