### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Warchant** [jsdom/whatwg-url#130]
You should be aware about security issue in `lodash.sortby` 4.7.0 
https://ossindex.sonatype.org/component/pkg:npm/lodash.sortby

**Comment by domenic** [comment]
Dupe of #127; same comments apply.

**Comment by chyzwar** [comment]
I have a hard time to understand why lodash.sortby is better than lodash. #127 does not provide justification. 

1. lodash.sortby is huge 5.1 kB MINIFIED + GZIPPED. It adds another module to project where lodash is already there.
2. lodash.sortby have security vulnerability warning. Even if it cannot be expoited we still need to explain that to our corporate masters. 
2. lodash plan to deprecate per method packages. By including lodash/sortBy only sortby and deps will get included not the whole lodash.
