### ISSUE TITLE
Depends on problemetic project tr46

### ISSUE THREAD

**Issue by jonassmedegaard** [jsdom/whatwg-url#138]
This project depends on https://github.com/Sebmaster/tr46.js which hasn't been updated in several years and covers only Unicode 10.0.0, and seems a 1-man project so even if fixed concretely by nudging same issue may likely reoccur.

It seems the only use of tr46 is for the function `tr46.toASCII`, applied only to domain part of URLs.

Seemingly viable alternatives:
 * https://github.com/hexonet/idna-uts46
 * https://github.com/bestiejs/punycode.js - if correctly understood that idna-uts46 is beneficial only _beyond_ domain part handling

**Comment by domenic** [comment]
We're happy with @Sebmaster's tr46, as well as its maintainer, who is a maintainer of this repository. If you have specific issues you can raise them.
