### ISSUE TITLE
All "jsdom/whatwg-url's components" say "ReferenceError: whatwgURL is not defined"

### ISSUE THREAD

**Issue by csharrison** [jsdom/whatwg-url#161]
This is an issue with the live viewer.

I tried this with multiple versions of Chrome (M83 and M85). It looks like we're crashing trying to construct the utf8Encoder TextEncoder, with the error "Uncaught TypeError: TextEncoder is not a constructor", no matter what URL I am trying to test.

Maybe a problem with how we are pulling in dependencies s.t. it's rewriting the built in TextEncoder?

**Comment by domenic** [comment]
Thanks for catching this. I didn't test the live viewer with some recent restructuring changes so something definitely could have gone wrong. I'll try to fix it ASAP.

**Comment by csharrison** [comment]
Thanks! This tool is my go-to for //url parsing bugs now :)
