### ISSUE TITLE
Unable to set an URL protocol

### ISSUE THREAD

**Issue by xmaysonnave** [jsdom/whatwg-url#163]
whatwg-url v8.1.0

Here is a jest unit under nodejs :

  ```
it('Parsing IPFS scheme', () => {
    const base = new URL('https://ipfs.bluelightav.org')
    const parsed =  new URL('ipfs://bafybeigrhoshyutoif6pfy5ion35asrd2ojt5fgip5btenwfsriujw3ryy')
    parsed.pathname = `/ipfs/${parsed.hostname}`
    parsed.protocol = base.protocol
    parsed.host = base.host
    expect(
      parsed.protocol === 'ipfs:' &&
        parsed.hostname === 'ipfs.bluelightav.org' &&
        parsed.pathname ===
          '/ipfs/bafybeigrhoshyutoif6pfy5ion35asrd2ojt5fgip5btenwfsriujw3ryy'
    ).toBeTruthy()
  })

```

This test is true however I didn't expect such result as the 'parsed.protocol' is set with base.protocol.
I expected parsed.protocol === 'https:' however parsed.protocol === 'ipfs:'

Am I missing something ?

Thanks

**Comment by TimothyGu** [comment]
Per URL Standard, you can't change a URL's scheme from [_special_](https://url.spec.whatwg.org/#special-scheme) to non-_special_, or vice versa. `https` is a special scheme, while `ipfs` is not. See https://url.spec.whatwg.org/#scheme-state, step 2.1.1–2. The fact that browsers seem to allow doing so is a long-standing browser bug, but other parsers like Node.js' URL class implements the same behavior.
