### ISSUE TITLE
webidl-conversions blows up react-native

### ISSUE THREAD

**Issue by djMax** [jsdom/whatwg-url#167]
I'm not fully clear on what's going on here, but the new version of webidl-conversions has this line:

```
    const asBigIntN = unsigned ? BigInt.asUintN : BigInt.asIntN;
```

RN does not have BigInt, and kaboom.

**Comment by domenic** [comment]
That's a shame. Our support matrix is Node.js though, so this isn't something we will be changing.

**Comment by karwa** [comment]
@domenic This also appears to break the live URL viewer in Safari 13.0.4.

The components view says `ReferenceError: Can't find variable: whatwgURL`, and the debug console points to this line, saying `Can't find variable: BigInt`.

**Comment by domenic** [comment]
Thankfully, Safari 14 supports BigInt, so we should be fine now!

**Comment by SamehElzamly** [comment]
has access any solution?

**Comment by SamehElzamly** [comment]
same error apper to me
