### ISSUE TITLE
[Firefox] Live URL Viewer: ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by valenting** [jsdom/whatwg-url#168]
```
Uncaught ReferenceError: SharedArrayBuffer is not defined
    [23]< https://jsdom.github.io/whatwg-url/whatwg-url.js:7631
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    [3]< https://jsdom.github.io/whatwg-url/whatwg-url.js:271
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    [24]< https://jsdom.github.io/whatwg-url/whatwg-url.js:7777
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    [12]< https://jsdom.github.io/whatwg-url/whatwg-url.js:2936
    o https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    r https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    <anonymous> https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    <anonymous> https://jsdom.github.io/whatwg-url/whatwg-url.js:1
    <anonymous> https://jsdom.github.io/whatwg-url/whatwg-url.js:1
```

The code at that location is:
```
const sabByteLengthGetter =
    Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength").get;
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes#API_changes) 
`SharedArrayBuffer objects are in principle always available, but unfortunately the constructor on the global object is hidden, unless the two headers mentioned above are set, for compatibility with web content.`

Not sure exactly where the code comes from, but the result is that the live URL viewer doesn't work in Firefox.

**Comment by domenic** [comment]
Hmm. whatwg-url itself targets Node.js, but live-url-viewer needs to work everywhere. Maybe we'll add a fake SAB to the global to work around this...

**Comment by brentonhouse** [comment]
@domenic  - Is there a polyfill for SharedArrayBuffer for those of us that use whatwg-url with non-node.js platforms (such as cross-platform native mobile solutions)?
