### ISSUE TITLE
why jsdom/whatwg-url and not Polymer/URL?

### ISSUE THREAD

**Issue by rodneyrehm** [jsdom/whatwg-url#18]
There already was a polyfill for the URL spec at [Polymer/URL](https://github.com/Polymer/URL) based off @annevk's original [url](https://github.com/annevk/url). What's the reason you created another implementation? I'm not accusing you of NIH, just curious…

**Comment by Sebmaster** [comment]
Polymer/URL is not fully compliant and (largly) unmaintained.

**Comment by domenic** [comment]
That's literally a year behind the spec, and doesn't follow the spec very closely anyway.

**Comment by rodneyrehm** [comment]
Makes sense, thx. Is your implementation limited to Node, or will it run in the browser as well? (I was going to replace the "parser" used in [URI.js](http://medialize.github.io/URI.js/) with a (less strict) implementation of the URL spec)

**Comment by Sebmaster** [comment]
It uses a bit of node stuff like Buffers, and requires ES6 features, but there's nothing which should prevent it from running in browsers by means of Browserify and similiar.
