### ISSUE TITLE
[security] Hostname Spoofing

### ISSUE THREAD

**Issue by ready-research** [jsdom/whatwg-url#193]
@domenic I have reported a security issue in huntr

https://www.huntr.dev/bounties/59fc3ef4-e827-4a17-981b-9ba7425ff400/

Please validate and let us know your opinion on this. Thank you.

**Comment by domenic** [comment]
Sorry, I'm not interested in using a third-party site that requires a login for tracking issues beyond GitHub. You're free to email the maintainers directly if you're not comfortable using GitHub yourself.
