### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by AnitaTang** [jsdom/whatwg-url#195]
While running my project, I encountered this error "ReferenceError: TextEncoder is not defined.        ..../node_modules/_whatwg-url@9.1.0@whatwg-url/dist/encoding.js:2:21". But it works well with lower version of whatwg-url. So what could be the reason? Thank U.

**Comment by domenic** [comment]
Are you using the latest version of Node v12 or higher? That is required as of the most recent major release.

**Comment by AnitaTang** [comment]
My Node version is v14.15.1

**Comment by domenic** [comment]
Try 14.17.5, the current supported LTS.

**Comment by AnitaTang** [comment]
It's a pity that this doesn't work.

**Comment by blissdev** [comment]
Hitting this issue as well, updating node in production environments isn't always a simple fix.

**Comment by domenic** [comment]
Sorry, use the old version if you can't upgrade. That's why we made it a major version bump.
