### ISSUE TITLE
"use strict" cause disable implicit globals TextEncoder, TextDecoder

### ISSUE THREAD

**Issue by jojosati** [jsdom/whatwg-url#197]
https://github.com/jsdom/whatwg-url/blob/08e598877a57b077247a19dfa1a82104c636a075/src/encoding.js#L1

Using "use strict" in encoding.js causes ReferenceError: TextEncoder is not defined #196 #195

**Comment by domenic** [comment]
Please provide an actual reproduction case.

**Comment by jojosati** [comment]
A note for my case, to solve ReferrenceError: TextEncoder is not defined.

The problem is I don't set proper Jest config, especially the [testEnvironment](https://jest-bot.github.io/jest/docs/configuration.html#testenvironment-string)
so default jest testEnvironment is "jsdom" and throw such error .

put this in the beginning of every test file
```
/**
 * @jest-environment node
 */
```

or set globally in package.json 
```
  "jest": {
    "testEnvironment": "node"
  },
```
