### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by santiagz** [jsdom/whatwg-url#198]
Got this error on [Docker](https://hub.docker.com/_/ubuntu) Ubuntu, `whatwg-url` got from `npm i whatwg-url`:
```js
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined

```

<details><summary>Full Error Log</summary>
<p>

#### yes, even hidden code blocks!

```bash
root@RestApiServer:/app/ApiServer# npm start

> apiserver@0.6.2 start /app/ApiServer
> node index.js

/app/ApiServer/node_modules/whatwg-url/dist/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/app/ApiServer/node_modules/whatwg-url/dist/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/ApiServer/node_modules/whatwg-url/dist/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apiserver@0.6.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apiserver@0.6.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-07T11_30_49_084Z-debug.log

```

</p>
</details>

Solution helped for me:

```bash
nano /app/MyProj/node_modules/whatwg-url/dist/encoding.js
```

and just add new line: 

```js
const { TextEncoder, TextDecoder } = require("util");
```

**Comment by domenic** [comment]
Please provide a complete reproduction, i.e. a file we can run `node test.js` and see the error. In other cases people have reported this issue it has been a Jest bug or bug in some other module.

**Comment by santiagz** [comment]
> 
> 
> Please provide a complete reproduction, i.e. a file we can run `node test.js` and see the error. In other cases people have reported this issue it has been a Jest bug or bug in some other module.

here it is: [Evian](https://github.com/santiagz/evian)

it's not a small project, 
don't think that problem in `index.js` 
cuz this error was only in Ubuntu Docker, 
win10 work fine

**Comment by domenic** [comment]
You need to provide a small reproduction that uses no third-party libraries or tools. Otherwise we assume it's a bug in the other libraries you are using.

**Comment by santiagz** [comment]
oh sir, 
i just report a little bug in whatwg-url package file, and I give you a solution.

I think this is a mongodb module that pulls the old version of the package whatwg-url .

**Comment by ChangXiaoning** [comment]
Hi I meet the same problem when using npm `jsdom`.
Reproduction:
1. Run cmd `npm install jsdom`;
2. Run following script:
```
//test.js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const { window } = new JSDOM(``, { runScripts: "outside-only" });

window.eval(`
  // This code executes in the jsdom global scope
  globalVariable = typeof XMLHttpRequest === "function";
`);

console.log(window.globalVariable === true);
```
Expected result: true is printed on the console
Actual result: const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined

**Comment by domenic** [comment]
I cannot reproduce that issue: https://runkit.com/embed/5v5p1m3gfuny

It may be that you are using an unsupported version of Node.js (i.e. not the latest release on the v12, v14, or v16 lines).

**Comment by ChangXiaoning** [comment]
Sorry for late reply. Yes, I am using Node.js v10. I am curious how versions of Node.js cause this issue.

**Comment by domenic** [comment]
Older versions of Node.js don't support APIs that whatwg-url uses.

**Comment by ChangXiaoning** [comment]
Can I get more information? Which API that whatwg-url uses causes this issue?
