### ISSUE TITLE
Explain c vs. c_str in a comment at the top

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#2]
From what I understand the spec uses _c_ (a "code point", which it writes as a string like `"@"`). We have `c`, a number, an `c_str`, the corresponding string. We pass them around together so that code which wants to do numeric comparison can use `c`, and code which wants to use string comparison can use `c_str`.

**Comment by Sebmaster** [comment]
`c_str` is not a thing anymore!
