### ISSUE TITLE
Possibility of backporting Buffer fix to 5.x

### ISSUE THREAD

**Issue by LinusU** [jsdom/whatwg-url#216]
Hey,

We are currently using version 5.x of this library in `node-fetch` 2.x, which still support older versions of Node.js. There is a lot of users that are still on 2.x for us, so we still maintain and try to fix things there. A recent backport from our 3.x to 2.x started triggering deprecation warnings from this library. ref: https://github.com/node-fetch/node-fetch/pull/1291#discussion_r729100963

Would you be open to a releasing a 5.0.1 version which just avoids the deprecation warnings?

If you could create a `5.x` branch from d34854a7af6ed1204f55d7da7761497bad350a7b, I would be happy to submit a pull request to that branch!

Thanks!

**Comment by domenic** [comment]
No, sorry, we only have the bandwidth to maintain a single version. You're welcome to fork the project and maintain your own separate fix.

**Comment by LinusU** [comment]
Understandable 👍 

To be clear though, I'm not asking you to maintain anything, just publish the version. But I understand if you don't want that...
