### ISSUE TITLE
Cursor resets on text entry

### ISSUE THREAD

**Issue by karwa** [jsdom/whatwg-url#223]
Hi!

I really love the live URL viewer; I use it all the time when I need to quickly check something. 

But there is one issue that is a little annoying: if I'm editing the middle of the URL, the cursor resets to the end each time I insert or delete a character.

Steps to reproduce:

1. Visit the Live Viewer
2. Enter some text in the "URL" box (it does not need to be a valid URL)
3. Click within the text to move the cursor
4. Insert or delete a character
5. The cursor will jump to the end of the text

I'm using Safari Version 15.0 (16612.1.29.41.4, 16612), on macOS 11.6.

**Comment by TimothyGu** [comment]
It looks to be a WebKit-specific bug, as I don't see that effect on Firefox or Chrome (on Linux), but do see that in Epiphany (GNOME Web).

**Comment by domenic** [comment]
Can you open an issue on https://bugs.webkit.org/ ?
