### ISSUE TITLE
Invalid ip address parsing

### ISSUE THREAD

**Issue by anonrig** [jsdom/whatwg-url#238]
Hi!

I'm the author of url-state-machine (https://github.com/anonrig/url-js). While doing some benchmarks I've found a bug with whatwg-url causing the following benchmark to fail.

```javascript
await benchmark(
  {
    "URL"() {
      return new URL("http://256.256.256.256.256", "http://other.com/");
    },
    "url-state-machine"() {
      return new URLStateMachine(
        "http://256.256.256.256.256",
        new URLStateMachine("http://other.com/").url,
      );
    },
    "whatwg-url"() {
      return new WHATWG.URL(
        "http://256.256.256.256.256",
        "http://other.com/",
      );
    },
  },
  { warmup: true },
);
```

Particularly the following command fails:

```javascript
console.log(new WHATWG.URL("http://256.256.256.256.256", "http://other.com/"));
```

The correct solution should have been:

```javascript
> new URL('http://256.256.256.256.256', 'http://other.com/')
URL {
  href: 'http://256.256.256.256.256/',
  origin: 'http://256.256.256.256.256',
  protocol: 'http:',
  username: '',
  password: '',
  host: '256.256.256.256.256',
  hostname: '256.256.256.256.256',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

**Comment by domenic** [comment]
`http://256.256.256.256.256` is an invalid URL that will not parse, per [the URL Standard's IPv6 parser](https://url.spec.whatwg.org/#concept-ipv6-parser):

> If ipv4Piece is greater than 255, [validation error](https://url.spec.whatwg.org/#validation-error), return failure.

So whatwg-url is correct here, and anything that does not give an error for such a URL is incorrect.

**Comment by anonrig** [comment]
You're right but the native URL implementation does not throw an error, which was vague.

**Comment by domenic** [comment]
It does in Chrome and Safari.
