### ISSUE TITLE
but parsing URL with IPv4 address as hostname?

### ISSUE THREAD

**Issue by derhuerst** [jsdom/whatwg-url#270]
```shell
mkdir bug
cd bug
npm init --yes
npm i whatwg-url@14
npm ls
# bug@1.0.0 /Users/j/playground/bug
# └── whatwg-url@14.0.0
node
```

```js
> const {parseURL} = await import('whatwg-url')
> parseURL('http://10.128.32.61:17000/').host
// 176169021
```

This also happens with `whatwg-url@13.0.0` btw.

**Comment by domenic** [comment]
This is as expected when using the [low-level `parseURL` API](https://github.com/jsdom/whatwg-url?tab=readme-ov-file#low-level-url-standard-api) and inspecting the internal URL record data structure. If you want to serialize the host back to a string, use `serializeHost`.

Or, just use [the high-level API](https://github.com/jsdom/whatwg-url?tab=readme-ov-file#the-url-and-urlsearchparams-classes).
