### ISSUE TITLE
URL Can contains invalid hostname

### ISSUE THREAD

**Issue by mardiros** [jsdom/whatwg-url#271]
Hi, coming from [pydantic](https://github.com/pydantic/pydantic/issues/9000)
That redirect me to [servo](https://github.com/servo/rust-url/issues/913) that redirect me here now.

The url validation specifis invalid host here
I https://url.spec.whatwg.org/#host-invalid-code-point

But actually the host validation is partially implemented. A hostname can neither starts nor ends with an hyphen.
But currently, this implementation says that `-x` is a valid hostname.

https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly8teC8=&base=YWJvdXQ6Ymxhbms=

**Comment by domenic** [comment]
This is a parser, not a validator. There are many invalid parseable URLs. This is discussed in the section of the spec you linked to.
