### ISSUE TITLE
I have angular v18 ssr when trying to connect to mongodb it gives errors about ” whatwg-url”

### ISSUE THREAD

**Issue by shady-ahmed-bdr** [jsdom/whatwg-url#274]
`node_modules>whatwg-url>lib>utils.js`  line 34

this happens only with Angular V17,18 for some unknown reason for me 
 error =>
![image](https://github.com/jsdom/whatwg-url/assets/67875381/b0459e20-22fa-4081-a376-0d83a4dbf461)

by the help of chatgpt i replaced 
`const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(async function* () {}).prototype)`

to this 

```
let AsyncIteratorPrototype;

try {
    // Check if async generator functions are supported
    const asyncGenFunction = async function* () {};
    // Verify that the async generator function has a prototype
    if (asyncGenFunction.prototype) {
        // Access AsyncIteratorPrototype
        AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(asyncGenFunction.prototype));
    } else {
        throw new Error('Async generators are not supported in this environment.');
    }
} catch (error) {
    console.error('Failed to assign AsyncIteratorPrototype:', error);
    // Provide a fallback or handle the error as needed
    AsyncIteratorPrototype = null; // Assigning null as a fallback
}
```

more details in [https://www.mongodb.com/community/forums/t/i-have-angular-v18-ssr-when-trying-to-connect-to-mongodb-it-gives-errors-about-whatwg-url/283236?u=shady_babloo_gamer](url)

**Comment by domenic** [comment]
Sorry, we cannot help debug third-party packages like Angular.

**Comment by intrepidOlivia** [comment]
This is also happening to me when I import this library into a unit test. I'm not using the Angular framework. I downgraded through the version number until I found the version where this problem starts. It starts happening in 8.2.0 (8.1.0 works fine). If anyone else runs into this problem, try using version 8.1.0 of whatwg-url for an immediate workaround.

I'll re-open this issue if I can create a minimal test case for it.

**Comment by shady-ahmed-bdr** [comment]
> This is also happening to me when I import this library into a unit test. I'm not using the Angular framework. I downgraded through the versions until I found where this problem starts. It starts happening in 8.2.0 (8.1.0 works fine). If anyone else runs into this problem, try using version 8.1.0 of whatwg-url for an immediate workaround.
> 
> I'll re-open this issue if I can create a minimal test case for it.

I had to learn about npm packages ,
i change it and deployed it under the name whatwg-url-ssr which lead me to modify mongodb package itself.
look use [mongodb-ngssr](https://www.npmjs.com/package/mongodb-ngssr)  it will work 
i hope i remember to update the package to latest .

**Comment by intrepidOlivia** [comment]
I have a minimal test case for this error. There must be something about it that makes it an edge case, since this error doesn't seem to have caused too many problems in the dev community since version 8 was released. But in my current project it is preventing me updating this library to the most recent version.

Minimal test case: https://github.com/intrepidOlivia/whatwg_test_case

**Comment by domenic** [comment]
That "minimal" test case uses many third-party packages:

```
    "@types/jest": "29.5.12",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
    "sinon": "^18.0.0",
    "ts-jest": "29.2.4",
    "typescript": "5.5.4",
    "whatwg-url": "8.2.0"
```

If you can get it to reproduce with only `whatwg-url`, then we can help. Otherwise, we cannot.

**Comment by intrepidOlivia** [comment]
Ah, good thing this library isn't meant to operate alongside any other common packages then. 

My full project has many many other packages, yet this is the only one that fails immediately on **import**. I helped isolate my use case here. Whoever the next person is who runs into this problem, maybe you can dig in further and see what the commonalities are between your case and mine.

**Comment by polif7** [comment]
Hi, right now everyone with Angular SSR have this [issue](https://www.mongodb.com/community/forums/t/i-have-angular-v18-ssr-when-trying-to-connect-to-mongodb-it-gives-errors-about-whatwg-url/283236/3).
Even solution is provided.
And here is a topic on angular-cli describing the [problem](https://github.com/angular/angular-cli/issues/27880) with reference to 
[this](https://github.com/angular/angular-cli/issues/27755).

**Comment by shady-ahmed-bdr** [comment]
> Hi, right now everyone with Angular SSR have this [issue](https://www.mongodb.com/community/forums/t/i-have-angular-v18-ssr-when-trying-to-connect-to-mongodb-it-gives-errors-about-whatwg-url/283236/3). Even solution is provided. And here is a topic on angular-cli describing the [problem](https://github.com/angular/angular-cli/issues/27880) with reference to [this](https://github.com/angular/angular-cli/issues/27755).

the problem appear only in dev mode, in production it works just fine, 
i made custom packages  from whatwg-url , mongodb-connection-string and finally mongodb-ngssr v6.7  not far from the current V6.11 
soo all u have to do run command  `npm i mongodb-ngssr`  and that only for development.  
@polif7

**Comment by shady-ahmed-bdr** [comment]
> @shady-ahmed-bdr thank you very much for your response! I managed to get this work by using `"externalDependencies": ["whatwg-url"]` flag in angular.json file.
> 
> But for me it's still not working in test/staging environment. `Error: Cannot find module 'whatwg-url'` How did you manage to get this to work? I'm using connect-mongo package, which has dependencies to mongodb package.


look mongodb driver works fine after `ng build` without any change in angular.json,
for the issue you are having, there is work around this, but u have to do it each time for new project setup.
1- delete package-lock file from main folder ( your project )
2- go to node_module folder and delete mongodb folder   
3- go to node_module>connect-mongo>package.json and modify mongodb to `"mongodb-ngssr": "^6.7.0",`  in the `"devDependencies"`
and tell me what is the result..
@polif7 
note: when it comes for production u need to switch to default mongodb for the latest driver.
