### ISSUE TITLE
Punycode deprecation warning on node js > 20

### ISSUE THREAD

**Issue by kuselan84** [jsdom/whatwg-url#275]
Following deprecation warning appear after update of node js to version 22:

`(node:64556) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
`

**Comment by domenic** [comment]
This package does not use the built-in punycode module so this is not the appropriate repository.

**Comment by graffhyrum** [comment]
The issue is likely from node-fetch,
see https://github.com/node-fetch/node-fetch/issues/1797

**Comment by spaquet** [comment]
You do have an indirect call in indirect-state-machine.js line 2 when you are calling `tr46`
this package calls punycode... so in a certain way you are using it as a sub-dependency, no?

**Comment by wojtekmaj** [comment]
@ve3 But that's version 5.0 or similar :D

**Comment by robbieaverill** [comment]
For others coming across this who may also be using older whatwg-url versions (probably not deliberately), there's a helpful solution here: https://github.com/jsdom/whatwg-url/issues/261#issuecomment-1791338293

Note that punycode was removed from this library at v9.0.0, so anything newer than that will remove the deprecation warning.
