### ISSUE TITLE
AVG detects `url-state-machine.js` as Trojan

### ISSUE THREAD

**Issue by morion4000** [jsdom/whatwg-url#280]
<img width="627" alt="Screenshot 2024-11-10 at 12 12 45" src="https://github.com/user-attachments/assets/a0163db9-768f-4a90-a903-097fe16a8934">

**Comment by lukBB** [comment]
same here

**Comment by Wellington01** [comment]
same here

**Comment by morion4000** [comment]
> In case someone needs a temporary fix:
> 
> My project was using whatwg-url@5.0.0 which was required by @supabase/node-fetch. Overriding to the latest version of whatwg-url fixed the Malware-Detection for now:
> 
> package.json: `"overrides": { "whatwg-url": "^14.0.0" }`

It works. Thank you!

**Comment by Niels-Baas** [comment]
Got the same within Norton could somebody explain why this can happen? And is it safe or

**Comment by Wellington01** [comment]
> Got the same within Norton could somebody explain why this can happen? And is it safe or

Researching to solve the problem, I realized that depending on the package you are using in the project, it forces a version of whatwg-url that uses the punycode package in the "url-state-machine.js" file, punycode had some security issues previously reported, in the most recent versions of whatwg-url the use of punycode was removed, so setting it to use the newer versions solves the problem.

**Comment by PatrickSocha** [comment]
+1 to this issue on Avast Business. File is quarantined.
