### ISSUE TITLE
Empty password not ok

### ISSUE THREAD

**Issue by nicolashenry** [jsdom/whatwg-url#34]
```javascript
var url = new URL("http://user:pass@test.com/");
url.password = "";
console.log(url.href); // "http://user:@test.com/"
```
The expected output is "http://user@test.com/" and not "http://user:@test.com/".

**Comment by Sebmaster** [comment]
You're right, the spec mentions this already. I'll see if I can release an update without breaking anything - the spec is in a considerable amount of flux / non-working state right now :confused:
