### ISSUE TITLE
Publish 1.0.0

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#41]
jsdom needs it: https://github.com/tmpvar/jsdom/pull/1265

**Comment by onlywei** [comment]
Is 1.0.0 the version after 0.6.5?

**Comment by domenic** [comment]
Hopefully!

**Comment by Sebmaster** [comment]
It's not out yet, there are still some issues to sort out in the jsdom part which might require changes so holding off for now.

**Comment by onlywei** [comment]
Is there any way to cut a release before 1.0.0 just to address this specific thing?
https://github.com/whatwg/url/issues/80

**Comment by Sebmaster** [comment]
1.0.0 is released :wink:

**Comment by mightyguava** [comment]
This is awesome! Will jsdom be cutting a release soon with this as well?

**Comment by domenic** [comment]
Yep, got a big 8.0.0 coming after I land https://github.com/tmpvar/jsdom/pull/1265
