### ISSUE TITLE
"browser" package.json field

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#46]
```json
"browser": "lib/browser.js"
```
lib/browser.js:
```js
module.exports = window.URL || window.webkitURL;
```

for browserify

**Comment by Sebmaster** [comment]
No, this package and the browser implemented URL object aren't necessarily the same (yet). No point doing this if the lib then produces inconsistent results. For example: chrome handles paths on windows differently than paths when running on Linux.

**Comment by stevenvachon** [comment]
How far off is https://github.com/Polymer/URL compared to this lib?

**Comment by Sebmaster** [comment]
It doesn't properly do encoding replacements and it hasn't been updated in a while (the spec has though, so probably a bit off there; I'd assume file paths/non-special schemas are most likely impacted there).

**Comment by stevenvachon** [comment]
Thanks!

**Comment by stevenvachon** [comment]
How about providing a browser version that relies on the browser's `URL` class, but builds around it to provide the additional functionality? Would the path inconsistencies cause issues there?

**Comment by Sebmaster** [comment]
The lib doesn't provide any additional functionality though, it just properly implements what's needed for the spec. Also there's no way to half-parse a URL, so it's not possible to use the URL object for the host part and re-implement path ourselves.

What are you expecting of relying on the browser's URL class instead of this library?

**Comment by stevenvachon** [comment]
Lower file size for front-end apps, mainly.

**Comment by stevenvachon** [comment]
Also, this library already does half parse URLs -- query strings are optionally parsed and in different ways.

**Comment by Sebmaster** [comment]
That's not what I was refering to. To know what to half-parse you have to know where in the string the half you want to parse starts. But to do that, you need to parse the whole URL.

**Comment by stevenvachon** [comment]
Why re-implement path at all?

**Comment by Sebmaster** [comment]
See before
> For example: chrome handles paths on windows differently than paths when running on Linux.

If you trust your browser(s) to follow the spec enough, you don't need this lib. If you want consistency, use it. There's no half-half.

**Comment by stevenvachon** [comment]
My goal is to use this for node, and use the browser's implementation when compiling with browserify.

**Comment by Sebmaster** [comment]
You can do that by writing a small file which just exports window.URL and specifying that to replace whatwg-url in your package.json.

**Comment by stevenvachon** [comment]
But there're functions available in this library that are not available in the browser implementations, are there not?

**Comment by Sebmaster** [comment]
No, the exported `URL` object should be totally equal. There are some exported util methods which you shouldn't have to worry about in browsers and wouldn't make sense to use with browser-native URL objects anyways.

**Comment by stevenvachon** [comment]
Okay, great!

The issue I've often run into with browserify is packages with larger dependencies -- I have to understand all parts of the sum to decide what should be excluded. I believe that this responsibility should fall into the package itself somehow. Someone wishing to browserify my lib will have to know to do what you described above.

**Comment by Sebmaster** [comment]
Shouldn't you be able to specify that in your lib so dependents don't have to know?

**Comment by stevenvachon** [comment]
How? My reading hadn't turned up anything a while back and even asking others led to a dead end.

**Comment by Sebmaster** [comment]
I'd assume the browser directive will work recursively - if you specify the whatwg-url redirection in your package, other packages requiring yours don't have to know about the whatwg-url vs URL problem.
