### ISSUE TITLE
"get the base" confusion

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#5]
Code says

```js
        // SPEC: says to use "get the base" algorithm,
        // but the base might've already been provided by the constructor.
        // Clarify!
```

I think the implementation here is not quite on-spec. If you provide a base URL to the constructor, then per https://url.spec.whatwg.org/#dom-url-urlurl-base, the internal getTheBase returns a (normalized, validated) version of the provided base.

So `getURL()` doesn't need a getTheBase argument. `init()` probably does, since `getAnchor()` or `mixinAnchor()` or whatever will need it.

I might be able to PR this in.

**Comment by Sebmaster** [comment]
Oh, I was under the impression `new URL("/abc")` worked on random pages. But just tried and it doesn't. Gonna change this then.
