### ISSUE TITLE
Parse relative URLs

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#54]
... containing only a path and hash. Is this possible? I know that the browser implementation of `URL` does not.

**Comment by Sebmaster** [comment]
No, this is a strict implementation according to the [URL spec](https://url.spec.whatwg.org/).

**Comment by stevenvachon** [comment]
What are our options then? And, why not modify the spec to support relative URLs?

**Comment by domenic** [comment]
First you'd have to specify what a relative URL is, and what data structure it parses to. Sounds like a large multi-month effort, with unclear benefit.

**Comment by stevenvachon** [comment]
https://github.com/whatwg/url/issues/136

**Comment by alwinb** [comment]
I have been working on an URL parser that supports relative URLs, while trying to be compatible with the WhatWG URL standard. 
,
