### ISSUE TITLE
Absolute url with relative base throws error

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#55]
```js
new URL("http://domain/path", "");
new URL("http://domain/path", "/path2/");
new URL("http://domain/path", "//domain2/path2/");
```

If the the input URL is absolute, the base shouldn't matter (unless it's not a string and not `undefined`). It probably shouldn't even be parsed in such a case.

**Comment by domenic** [comment]
Again, we're just following the standard here. This is not a bug in jsdom/whatwg-url.

Anyway, you can open a bug on the standard if you want. But in general input validation is seen as a good thing.
