### ISSUE TITLE
toJSON() serialization

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#56]
```js
console.log( JSON.stringify( new (require("whatwg-url").URL)("http://domain/") ) )
```
produces:
```js
{}
```

**Comment by Sebmaster** [comment]
What's the issue?

**Comment by stevenvachon** [comment]
https://github.com/whatwg/url/issues/137

**Comment by domenic** [comment]
Please stop opening spec bugs here... The spec has no toJSON, so do we.

**Comment by stevenvachon** [comment]
You said that it should serialize to components... in my above example this implementation does not.

**Comment by domenic** [comment]
That's a matter of how your browser prints things. It doesn't affect implementation of the library.

**Comment by stevenvachon** [comment]
Prints things? It's a string.

**Comment by domenic** [comment]
Sorry, I was confused about console.log vs. JSON.stringify. But regardless, we are following the spec here.
