### ISSUE TITLE
bug in parsing file:

### ISSUE THREAD

**Issue by bmeck** [jsdom/whatwg-url#67]
Some oddities show up while parsing file urls across all the envs I am looking at. 

```js
u = new URL('file://x#y')
u.href // 'file://x/#y'
``` 

The extra `/` shouldn't be there for this one.

**Comment by Sebmaster** [comment]
I think it should. What's happening here is that `x` is actually the file host. If you do a tripple slash (implicit local host) `(new x.URL('file:///x#y')).href`, it'll work fine.

**Comment by domenic** [comment]
Browsers do seem pretty inconsistent here: https://quuz.org/url/liveview.html#file://x#y But I think the spec/whatwg-url's interpretation is fairly reasonable...

**Comment by annevk** [comment]
@bmeck what's the expected result in terms of host, path, and fragment?

**Comment by bmeck** [comment]
@annevk reading https://url.spec.whatwg.org/#file-host-state actually @domenic is right, browsers should treat `x` as the host. IDC what it is as long as consistency is achieved.
