### ISSUE TITLE
Property descriptors are wrong

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#7]
Currently non-enumerable and non-configurable, but they should be enumerable and configurable.

To fix this it's probably easiest to move from Object.defineProperty to just object literals with get x() {} and set x(v) {}.

**Comment by Sebmaster** [comment]
Fixed with a57743e.

**Comment by stevenvachon** [comment]
They're still appearing as enumerable:
```js
var URL=require("whatwg-url").URL;
console.log( new URL("http://asdf/") )
```
prints:
```
URL {}
```

**Comment by domenic** [comment]
You can't tell whether something's enumerable or not by printing it.

**Comment by stevenvachon** [comment]
Node's `console.log()` doesn't print prototyped properties/methods.
