### ISSUE TITLE
do browsers use punycode?

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#78]
I don't see any mention of "punycode" in the spec, and Chrome behaves differently:
```js
new URL("http://faß.ExAmPlE").hostname
//-> fass.example
```

I don't know enough about text encoding to know if punycode is different from ascii/unicode

**Comment by domenic** [comment]
Yes. It's in the spec as the ToASCII algorithm.

If you have browser bugs to report that's best reported on browsers. If you have questions about the spec that's best reported on the spec. whatwg-url is just faithfully implementing the spec.

**Comment by domenic** [comment]
Although I guess since you were probably looking at the code you were referring to our use of the punycode package, not the punycode concept in general. We use the ucs2.decode function which is necessary for implementing the parts of the spec that involve decoding JavaScript strings into bytes.

**Comment by stevenvachon** [comment]
Thank you.
