### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#8]
_Not_ necessary for v1. But I think that it would be really good, for both the implementation and the URL spec itself, to add some code coverage so we get some idea of how complete the test cases in web-platform-tests are, and can create new ones to target under-tested areas of the spec.

**Comment by Sebmaster** [comment]
For information, coverage currently:

```
=============================== Coverage summary ===============================
Statements   : 75.44% ( 467/619 )
Branches     : 69.51% ( 383/551 )
Functions    : 71.67% ( 43/60 )
Lines        : 75.44% ( 467/619 )
================================================================================
```
