### ISSUE TITLE
Creating URL objects seems broken

### ISSUE THREAD

**Issue by AlexTes** [jsdom/whatwg-url#86]
The paths look all wrong, but then the building looks magic 😅.

The following gives me an empty URL instance but works with Node's (v7) WHATWG-URL.
```js
const wURL = require('whatwg-url');
new wURL.URL('https://alextes.me'); // URL {}
```

Sorry, I can't be more helpful here 🙁. Have an emoji 👭.

**Comment by domenic** [comment]
It's not empty. It's just that Node's console.log doesn't print getters on the prototype.

All the properties work fine.

**Comment by AlexTes** [comment]
Yup, the `href` property prints totally fine.
Sorry for wasting your time!

**Comment by stevenvachon** [comment]
@AlexTes Please read the documentation: `isURL.lenient(url)`

**Comment by AlexTes** [comment]
@stevenvachon oh hey! thanks. My bad!
