### ISSUE TITLE
Validate IPv4 addresses

### ISSUE THREAD

**Issue by Sebmaster** [jsdom/whatwg-url#9]
It seems like the spec doesn't contains any steps to validate IPv4 addresses, but the test cases in the web-platform-tests repository include some which validate proper handling of IPv4 addresses.

@annevk is that missing from the spec, or did I miss it somewhere?

**Comment by domenic** [comment]
Maybe it is this subset of the IPv6 parser? https://url.spec.whatwg.org/#concept-ipv6-parser-ipv4

**Comment by Sebmaster** [comment]
From what I've seen the ipv6 parser is only executed if host starts with \[ and ends with \].

**Comment by annevk** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26431

Seems the tests may be ahead of the specification...

**Comment by Sebmaster** [comment]
Fixed by 616baa2d82f31f81e13d9b108dd974980dbe6d4f.

Seems like one of the web-platform-tests is wrong though.

**Comment by annevk** [comment]
Which one?

**Comment by Sebmaster** [comment]
@annevk 
`http://%30%78%63%30%2e%30%32%35%30.01%2e` seems to be weird. Apparently the test expects it to not get parsed as IPv4. Chrome parses it as ipv4, Firefox doesn't even try and leaves it urlencoded.

**Comment by annevk** [comment]
Submitted a fix for that test. Thanks.

**Comment by martinthomson** [comment]
I'm getting three errors on https://jsdom.github.io/whatwg-url/#url=aHR0cDovLzB4N2YwMDAwMDEv&base=YWJvdXQ6Ymxhbms= which is the perfectly valid (if somewhat insane) "http://0x7f000001/".  The parsing results appear to be just fine, but the errors are all wrong.

**Comment by domenic** [comment]
Please open such issues on the URL Standard, instead of commenting on closed-for-11-years bugs on a JavaScript implementation of that standard.
