### ISSUE TITLE
Validation error should not terminate the parser

### ISSUE THREAD

**Issue by GPHemsley** [jsdom/whatwg-url#92]
> A validation error indicates a mismatch between input and valid input. User agents, especially conformance checkers, are encouraged to report them somewhere.
>
> **NOTE:**
> > A validation error does not mean that the parser terminates. Termination of a parser is always stated explicitly, e.g., through a return statement.
> > 
> > It is useful to signal validation errors as error-handling can be non-intuitive, legacy user agents might not implement correct error-handling, and the intent of what is written might be unclear to other developers.

It seems that this script throws 'TypeError: Invalid URL' upon a validation error, but that terminates the parser, preventing the availability of the parsed URL parts. This confuses, for example, [Live URL Viewer](https://quuz.org/url/liveview.html).

**Comment by TimothyGu** [comment]
Can you provide an example of one such validation error that terminates the entire parser?

**Comment by GPHemsley** [comment]
https://quuz.org/url/liveview.html#http://0x100000000/test

**Comment by domenic** [comment]
I don't think the root cause analysis is correct here, as we very much separate validation errors and returning failure in the code. But we can take this as bug report for those two URLs, at least.

**Comment by domenic** [comment]
Note also that live URL viewer uses an outdated version of whatwg-url. Did you test against the latest version from npm?

**Comment by TimothyGu** [comment]
The second URL fails because of step 9 in [IPv4 parser](https://url.spec.whatwg.org/#concept-ipv4-parser). Haven't been able to figure out why the first fails yet, as the host parser accepts `0x1000000000`.

**Comment by GPHemsley** [comment]
Nope, I didn't get any further than the webpage. Does the latest version of whatwg-url pass all the web platform tests?

**Comment by GPHemsley** [comment]
@TimothyGu Oh, good point. I came up with that one on the fly, and Firefox seems to have parsed it out fine. I guess that's a browser bug.

**Comment by domenic** [comment]
> Does the latest version of whatwg-url pass all the web platform tests?

We haven't yet implemented https://github.com/whatwg/url/commit/dc9d83106cada9af507bf37dee3973de97b020fd (i.e. the tests at https://github.com/w3c/web-platform-tests/commit/ded8ffe86722118bf035cf2e48c9dbf199aa1f92), but we're up to date otherwise.

**Comment by domenic** [comment]
http://0x100000000/test fails because we reach the IPv4 parser step 10:

> If the last item in numbers is greater than or equal to 256<sup>(5 − the number of items in numbers)</sup>, validation error, return failure.

Since 0x100000000 === 4294967296 is equal to 256<sup>(5 − 1)</sup> === 4294967296, we return failure, as expected.

So it appears there is no whatwg-url bug here. But perhaps some good failure test cases to add to the test suite; I'll do that!

**Comment by GPHemsley** [comment]
Bug was in my code, not yours. Sorry for the noise.
