### ISSUE TITLE
Cannot find module webidl-conversions

### ISSUE THREAD

**Issue by ForbesLindesay** [jsdom/whatwg-url#93]
```
npm install whatwg-url
node
> require('whatwg-url').parseURL('javascript:alert(1)')
Error: Cannot find module 'webidl-conversions'
```

**Comment by domenic** [comment]
Must be something wrong with your npm: https://github.com/jsdom/whatwg-url/blob/e6c485ee0f516ca2467fc87e0d240d8363a2cb8a/package.json#L14

**Comment by ForbesLindesay** [comment]
Doesn't seem to be happening now. Probably just caused by the new npm version combined with package-lock weirdness.
