### ISSUE TITLE
"new.target" can't be minified

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#96]
In URL.js:
```js
function URL(url) {
  if (!new.target) {
    throw new TypeError(
      "Failed to construct 'URL'. Please use the 'new' operator; this constructor cannot be called as a function."
    );
  }
```

Where does this variable `new` even come from?

**Comment by stevenvachon** [comment]
Aye... new ES2015 stuff: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

Babel [doesn't support it yet](https://github.com/babel/babel/issues/1088).

**Comment by TimothyGu** [comment]
It can be minified if you use a new enough minifer like [babili](https://github.com/babel/babili) or [uglify-es](https://www.npmjs.com/package/uglify-es).

**Comment by stevenvachon** [comment]
Doesn't uglify-es perform ES2015 optimizations, like outputting arrow functions in situations where `this` and `arguments` are not needed?

**Comment by TimothyGu** [comment]
@stevenvachon Not sure, I haven't used uglify-es, only babili. But I wouldn't say that's a bad thing.

**Comment by stevenvachon** [comment]
It's bad if you want to support older ES5-only browsers.

**Comment by TimothyGu** [comment]
If you want to support older browsers you'd have to run this module through Babel or something like that in the first place for much more than just `new.target`, do you not?

**Comment by stevenvachon** [comment]
I just replaced `new.target` with `this instanceof this.constructor` for now.

**Comment by aaarichter** [comment]
just out of curiosity. What is the point of making a polyfill with the latest ES syntax when common used transpilers don't recognize it making the polyfill worthless for older browsers.

The readme should at least state what polyfills are required for `whatwg-url`  and what babel modules need to be used.

**Comment by Sebmaster** [comment]
> just out of curiosity. What is the point of making a polyfill with the latest ES syntax when common used transpilers don't recognize it making the polyfill worthless for older browsers.

This polyfill was intended for node before it got its own URL implementation.

**Comment by aaarichter** [comment]
@Sebmaster thanks for clarifying. Are there any plans to make it compatible for web browsers?

**Comment by stevenvachon** [comment]
@aaarichter try [universal-url](https://npmjs.com/universal-url) before @domenic deletes this comment.

**Comment by aaarichter** [comment]
thanks @stevenvachon .

I had to load all ES6 modules of core-js to get whatwg-url in IE11 working without JS error. but this adds lots of kb (unzipped, unminified) to my bundle

**Comment by stevenvachon** [comment]
@aaarichter read the readme.
