### ISSUE TITLE
delete() and "?"

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#97]
```js
const nativeURL = require("url").URL;
const shimmedURL = require("whatwg-url").URL;

const native = new nativeURL("http://host/?param");
native.searchParams.delete("param");
native.href;
//-> http://host/

const shimmed = new shimmedURL("http://host/?param");
shimmed.searchParams.delete("param");
shimmed.href;
//-> http://host/?
```

Pretty sure that the native one is correct. @TimothyGu ?

**Comment by TimothyGu** [comment]
What do browsers do?

**Comment by TimothyGu** [comment]
I'm reasonably certain that Node.js' behavior is the faulty one here…

**Comment by stevenvachon** [comment]
Chrome and Firefox both behave like Node.js

**Comment by stevenvachon** [comment]
Ok, https://github.com/nodejs/node/issues/14020

**Comment by TimothyGu** [comment]
Added this case to WPT in https://github.com/w3c/web-platform-tests/pull/6445. Will apply the fix to Node.js after the PR is merged.

**Comment by TimothyGu** [comment]
This should be reopened now that https://github.com/whatwg/url/pull/336 has been merged.
