### ISSUE TITLE
mailto IDNAs?

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#98]
```js
new URL("mailto:a@:*&^:") // parses
new URL("http://a@:*&^:") // throws
```

**Comment by Sebmaster** [comment]
Looks pretty good to me. What's the supposed issue here?

**Comment by stevenvachon** [comment]
`mailto` URLs don't appear to have their hostnames validated for IDNA compliance.

**Comment by domenic** [comment]
Please provide more helpful issue descriptions in the future. This is the second useless issue opened by you.

mailto: URLs do not have hostnames; they only have paths.

**Comment by Sebmaster** [comment]
Mailto URLs don't have a hostname. They are pure data urls.

**Comment by stevenvachon** [comment]
@domenic relax.

https://github.com/whatwg/url/issues/331
